### ISSUE TITLE
Simply doesn't work

### ISSUE THREAD

**Issue by jcollum** [atom-compare-files/atom-compare-files#48]
Two files in tree: `.temp/comparison - api`, `.temp/comparison - rabbit`. Selecting both in folder tree then selecting Packages -> Compare Files -> Compare. 

Nothing happens. Something is supposed to happen here right? 

OSX, Atom 1.12.7, tool 0.8.0

Installed Split Diff instead, it works fine.

**Comment by ParitoshBh** [comment]
Refer to the usage - https://github.com/atom-compare-files/atom-compare-files#usage

You need to first select Packages -> Compare Files -> Compare and then select 2 files.

Closing this since it isn't an issue.
