### ISSUE TITLE
Deprecated calls

### ISSUE THREAD

**Issue by danbrennerarc** [atom-compare-files/atom-compare-files#55]
Atom now uses ES6 Promises instead of Q. Call promise.then instead of promise.done
Report Issue
Promise.done - <embedded>:1661:11
atom-workspace.compare - C:\Users\dan.brenner\.atom\packages\compare-files\lib\compare-files.js:81:11
CommandRegistry.handleCommandEvent - <embedded>:18816:35
handleCommandEvent - <embedded>:18554:65
CommandRegistry.dispatch - <embedded>:18717:25
AtomEnvironment.dispatchApplicationMenuCommand - <embedded>:1553:34

**Comment by GregPlowman** [comment]
Xref #49, #56

**Comment by ParitoshBh** [comment]
Closing. Similar issue exists.
