### ISSUE TITLE
Promise.done is deprecated.

### ISSUE THREAD

**Issue by GregPlowman** [atom-compare-files/atom-compare-files#56]
Atom now uses ES6 Promises instead of Q. Call promise.then instead of promise.done

**Comment by GregPlowman** [comment]
Maybe a dup of issue #49, which was apparently fixed by PR #51 
But latest release appears to be 0.8.0 on Sep 5, 2016, which wouldn't include this fix.

Perhaps tag a new release?

**Comment by ParitoshBh** [comment]
Aha. Yeah, there was a PR accepted but never released. Original developer was courteous enough to add me as part of maintainer but before even beginning to think about releasing an update, I'd like to have a short discussion about future of this plugin. Any thoughts?

**Comment by GregPlowman** [comment]
Well, I'm using it at the moment, but I really haven't looked for alternatives. 
Are there any better plugins for comparing files? If so then maybe just point users to those alternatives.

**Comment by ParitoshBh** [comment]
I couldn't find one (or didn't give enough time to do so) and hence found this plugin in first place!

**Comment by ParitoshBh** [comment]
Published a new release. This issue should be resolved now.
